- overall: 3.3.1
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.3.1.a.jqr
    test_count: 6
  - name: 3.3.1.b.jqr
    test_count: 3
  - name: 3.3.1.c.jqr
    test_count: 3
  - name: 3.3.1.d.jqr
    test_count: 3
  - name: 3.3.1.e.jqr
    test_count: 5
  - name: 3.3.1.f.jqr
    test_count: 3
  - name: 3.3.1.g.jqr
    test_count: 4
