- overall: 3.1.19
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.1.19.a.jqr                # name of the test suite to load from in the xml
    test_count: 3                   # number of tests to find in the test suite 
  - name: 3.1.19.b.jqr
    test_count: 3
  - name: 3.1.19.c.jqr
    test_count: 3
  - name: 3.1.19.d.jqr
    test_count: 3
  - name: 3.1.19.e.jqr
    test_count: 4
  - name: 3.1.19.f.jqr
    test_count: 3
