- overall: 3.7.2
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.7.2.a.jqr                # name of the test suite to load from in the xml
    test_count: 11                   # number of tests to find in the test suite 
  - name: 3.7.2.b.jqr
    test_count: 10
  - name: 3.7.2.c.jqr
    test_count: 8
  - name: 3.7.2.d.jqr                
    test_count: 5                  
  - name: 3.7.2.e.jqr
    test_count: 10
  - name: 3.7.2.f.jqr
    test_count: 7
  - name: 3.7.2.g.jqr
    test_count: 8
  - name: 3.7.2.h.jqr
    test_count: 10
