- overall: 3.1.23
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.1.23.a.jqr                # name of the test suite to load from in the xml
    test_count: 5                     # number of tests to find in the test suite 
  - name: 3.1.23.b.jqr
    test_count: 7
  - name: 3.1.23.c.jqr
    test_count: 7
  - name: 3.1.23.d.jqr
    test_count: 4
  - name: 3.1.23.e.jqr
    test_count: 3
  - name: 3.1.23.f.jqr
    test_count: 3
  - name: 3.1.23.g.jqr
    test_count: 3
  - name: 3.1.23.h.jqr
    test_count: 3
  - name: 3.1.23.i.jqr
    test_count: 4
  - name: 3.1.23.j.jqr
    test_count: 5
  - name: 3.1.23.k.jqr
    test_count: 3
  - name: 3.1.23.l.jqr
    test_count: 3
  - name: 3.1.23.m.jqr
    test_count: 3
  - name: 3.1.23.n.jqr
    test_count: 3
