- overall: 3.1.10
  test_files: [./build/3.1.10_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: jqr_pointers_tests                # name of the test suite to load from in the xml
    test_count: 6                    # number of tests to find in the test suite 
