- overall: 3.1.8
  test_files: [./build/3.1.8_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: "functions test suite"       # name of the test suite to load from in the xml
    test_count: 8                  # number of tests to find in the test suite 
