- overall: 3.5.1
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.5.1.a.jqr                # name of the test suite to load from in the xml
    test_count: 6                   # number of tests to find in the test suite 
  - name: 3.5.1.b.jqr
    test_count: 6
  - name: 3.5.1.c.jqr
    test_count: 6
  - name: 3.5.1.d.jqr
    test_count: 9
  - name: 3.5.1.e.jqr
    test_count: 7
