- overall: 3.2.1
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.2.1.a.jqr                # name of the test suite to load from in the xml
    test_count: 6                   # number of tests to find in the test suite 
  - name: 3.2.1.b.jqr
    test_count: 5
  - name: 3.2.1.c.jqr
    test_count: 4
  - name: 3.2.1.d.jqr
    test_count: 5
  - name: 3.2.1.e.jqr
    test_count: 5
  - name: 3.2.1.f.jqr
    test_count: 2
  - name: 3.2.1.g.jqr
    test_count: 4
  - name: 3.2.1.h.jqr
    test_count: 4
  - name: 3.2.1.i.jqr
    test_count: 4
  - name: 3.2.1.j.jqr
    test_count: 4
  - name: 3.2.1.k.jqr
    test_count: 2
  - name: 3.2.1.l.jqr
    test_count: 2
  - name: 3.2.1.m.jqr
    test_count: 3
  - name: 3.2.1.n.jqr
    test_count: 4
  - name: 3.2.1.o.jqr
    test_count: 4
