- overall: 3.2.6
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.2.6               # name of the test suite to load from in the xml
    test_count: 6
