- overall: 3.1.15
  test_files: [./build/3.1.15_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: state_machine_tests   # name of the test suite to load from in the xml
    test_count: 1                    # number of tests to find in the test suite 

