- overall: 3.7.1
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.7.1.a.jqr                # name of the test suite to load from in the xml
    test_count: 8                   # number of tests to find in the test suite 
  - name: 3.7.1.b.jqr
    test_count: 4
  - name: 3.7.1.c.jqr
    test_count: 22
  - name: 3.7.1.d.jqr                
    test_count: 4                  
  - name: 3.7.1.e.jqr
    test_count: 2
  - name: 3.7.1.f.jqr
    test_count: 9
