- overall: 3.1.12
  test_files: [./build/3.1.12_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: "jqr_conditionals_tests"               # name of the test suite to load from in the xml
    test_count: 12                    # number of tests to find in the test suite 
