- overall: 3.3.9
  test_files: [./build/3.3.9_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: stacks_tests                # name of the test suite to load from in the xml
    test_count: 8                    # number of tests to find in the test suite 
