- overall: 3.1.9
  test_files: [./build/3.1.9_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: "input_validation_tests"          # name of the test suite to load from in the xml
    test_count: 2                    # number of tests to find in the test suite 
