- overall: 3.5.2
  test_files: [./build/3.5.2_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: "signal test suite"                # name of the test suite to load from in the xml
    test_count: 4                    # number of tests to find in the test suite 
  - name: "interrupt test suite"                # name of the test suite to load from in the xml
    test_count: 4                    # number of tests to find in the test suite 
