- overall: 3.1.24
  test_files: [./build/3.1.24_exe-Results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: "threadpool test suite"                # name of the test suite to load from in the xml
    test_count: 9                    # number of tests to find in the test suite 
