- overall: 3.8.4
  test_files: [suite_results.xml]    # parsed relative to the location of this file
  sub_items:
  - name: 3.8.4.jqr                # name of the test suite to load from in the xml
    test_count: 4                    # number of tests to find in the test suite 

